apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-init-sql
data: 
  init.sql: |
    CREATE DATABASE gitlab_main;
    CREATE DATABASE gitlab_ci;
    GRANT ALL PRIVILEGES ON DATABASE gitlab_main TO gitlab;
    GRANT ALL PRIVILEGES ON DATABASE gitlab_ci TO gitlab;
