apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-init-sql
data: 
  init.sql: |
    CREATE DATABASE gitlab-main;
    CREATE DATABASE gitlab-ci;
    GRANT ALL PRIVILEGES ON DATABASE gitlab-main TO gitlab;
    GRANT ALL PRIVILEGES ON DATABASE gitlab-ci TO gitlab;
